[package]
name = "arkworks-gadgets"
version = "0.1.0"
authors = ["Drew Stone <drewstone329@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webb-crypto-primitives = { git = "https://github.com/webb-tools/crypto-primitives", package = "ark-crypto-primitives", rev = "c0056f7caeebc1537c663ac3fde5f770350b0f8c", features = ["r1cs"] }
ark-ff = { version = "^0.2.0", default-features = false }
ark-std = { version = "^0.2.0", default-features = false }
ark-r1cs-std = { version = "^0.2.0", default-features = false }
ark-relations = { version = "^0.2.0", default-features = false }
ark-ed-on-bn254 = { version = "^0.2.0", default-features = false, features = [ "r1cs" ] }
ark-bls12-381 = { version = "^0.2.0", default-features = false, features = [ "curve" ] }
ark-marlin = {version = "^0.2.0", default-features = false }
blake2 = { version = "0.9", default-features = false }
ark-poly-commit = { version = "^0.2.0", default-features = false }
ark-poly = { version = "^0.2.0", default-features = false }

[features]
default = []
r1cs = []