[package]
name = "arkworks-gadgets"
version = "0.1.0"
authors = ["Drew Stone <drewstone329@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webb-crypto-primitives = { git = "https://github.com/webb-tools/crypto-primitives", package = "ark-crypto-primitives", rev = "e42efdd" }
ark-crypto-primitives = "0.2.0"
ark-ff = { version = "^0.2.0", default-features = false }
ark-std = { version = "^0.2.0", default-features = false }
ark-r1cs-std = { version = "^0.2.0", default-features = false }
ark-relations = { version = "^0.2.0", default-features = false }

[features]
default = []
r1cs = []